<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <None Update="base-fingerprint.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Patcher\base-fingerprint.json</Link>
    </None>
    <None Update="Content\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Patcher\Content\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>
</Project>
